README.md, jenkins/templates/gh-secret.yaml
devhub now uses a github access token, i'm adding a template to the tools for awareness that the secret is required before building
=> add secrets template for github token

openshift/dc.yaml
Just updating the number of replicas so we are sure to survive maintenance with no blips.
=> Increase replica count to 2 for dev hub static web pod.

app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js, app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
Before this PR, if a markdown file had a `required` front matter property that was not being included
=> prevent build from failing if descriptions are missing in front matter

app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js
Any siphon nodes that have an external resourcePath are now unfurled
- integrated externalUnfurlPlugin
- fixed an issue preventing unfurling
=> Integrate external link unfurling

app-web/gatsby-node.js, app-web/gatsby/modifyWebpackConfig.js, app-web/gatsby/onCreatePage.js, app-web/src/constants/routes.js
**Please note** these changes are very specific to gatsby v1 and ***will*** break on upgrade to gatsby v2
Another step in the dynamic filtering feature. Filtering will be done via 'restful routes'. 
IE navigating to `/resources/components` will just re render the index page to show only cards that are `resourceType === 'components'`
During the navigation process, gatsby will actually look for a static site at the path `/resources/components`. The following changes tells gatsby to treat this route as dynamic and client side rendered only. 
- added a hook for `onCreatePage` to treat any routes `/resources/*` as client side rendered
- did some code cleanup in the `gatsby-node.js`
=> Add dynamic page create to gatsby configurations

app-web/src/hoc/TemplateLayout.js
Caused by a change to the graphql siphon schema.
Updated propTypes to prevent this issue from happening again.
=> Github Link in markdown template pages not working fix

app-web/__mocks__/got.js, app-web/__mocks__/puppeteer.js, app-web/package-lock.json, app-web/package.json, app-web/plugins/gatsby-source-github-all/utils/plugins.js
This issue was caused due to the unfurling plugin not being able to fully render the signing tool website. The singing tool website is client side rendered and so none of the HTML is available immediately on a simple http request.
This was resolved by actually 'rendering' the signing tool in a headless browser to get the evaluated HTML after the react javascript renderings are complete
=> Fix issue where Signing Tool Card was displaying Title: React App with no Description

app-web/__tests__/components/__snapshots__/PrimaryFooter.test.js.snap, app-web/gatsby/createPages.js, app-web/src/components/PrimaryFooter/PrimaryFooter.js, app-web/src/hoc/GithubTemplateLayout.js, app-web/src/hoc/TemplateLayout.module.css, app-web/src/templates/SourceGithubHTML.js, app-web/src/templates/SourceGithubMarkdown.js
The page creation initially was only based on mediaType (ie page templates for markdowns vs html).
This led to templates that were strongly tied to github sources. Since Siphon can assign different source types as they are supported. The way templates are chosen to create a page from a siphon node has been refactored.
- Updated createPages logic to choose templates based on source type
- Renamed Template files to be more related for github source types
=> Refactored Gatsby CreatePages to choose template based on source type

app-web/gatsby-config.js, app-web/package-lock.json, app-web/package.json
Internal Navigation for a md document wasn't working in devhub
- this has been fixed by adding the auto link headers transformer plugin
*** IMPORTANT ***
The version of the npm auto link headers package has been purposely set to `1.4.19` as that is the last stable version that is compatible with Gatsby V1, in reality this plugin is already in 2.x.x and so we will need to upgrade this when we upgrade our app the Gatsby V2
=> add auto link headers

app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js
We found an issue where markdown files may have an 'ignore' front matter property set to true, it would still create a card component which would link to a page that hadn't be created. 
This was found because there was some logic in the createPages to prevent pages from being created in the node but the card components graphql did not share a similar logic. To circumvent this issue all together, the approach i took was prevent graphql nodes from being created if they have an 'ignore: true' front matter property. 
- metadata property now includes 'ignore'
- source nodes now filter out files that have a ignore: true metadata property
- added unit tests for said filtering function
=> Bug: Adding ignore to frontmatter still creates a card that goes to no where

app-web/.prettierrc, app-web/__fixtures__/plugin-fixtures.js, app-web/__tests__/components/Card.test.js, app-web/__tests__/pages/Index.test.js, app-web/__tests__/redux/uiActionCreators.test.js, app-web/gatsby/createPages.js, app-web/gatsby/modifyWebpackConfig.js, app-web/plugins/gatsby-remark-path-transform/__tests__/utils.test.js, app-web/plugins/gatsby-remark-path-transform/index.js, app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js, app-web/plugins/gatsby-source-github-all/__tests__/helpers.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js, app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/constants.js, app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js, app-web/src/components/NavigationItems/NavigationItems.js, app-web/src/components/SourceNavigation/SourceNavigation.js, app-web/src/hoc/Layout.js, docs/registerRepo.md, docs/siphon.md
Siphon now supports a persona attribute in the registry yaml. The **persona** is just another key/value pair that allows for filtering *by persona* in the front end. The persona attribute in the registry is 'inherited' by markdown github sources. Overriding individual markdown files is supported as well with a markdown `persona` property. 
- added support for persona in registry
- added support for persona in markdown files
- updated docs
- updated siphon graphql schema a tiny bit
=> Add support for adding a 'persona' attribute to siphon

app-web/__mocks__/html-metadata.js, app-web/__mocks__/valid-url.js, app-web/package-lock.json, app-web/package.json, app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js
This is a composite issue.
twitter card images that were not absolute to the domain would not load in the devhub
twitter card image properties were not being parsed correctly by the metascraper library
- added some logic to the external unfurl plugin to preprend the domain if the image was !== /^https?/
- changed metascraping library for another one that seems to be more predictable
=> Fix issue where external resource image may not unfurl

app-web/plugins/gatsby-source-github-all/utils/plugins.js
This fixes the issue were twitter card/open graph images, that were formatted as valid web uris `(eg https://www..)`, would not unfurl correctly in siphon
=> fix an issue where twitter/opengraph urls that were web uris would not unfurl

app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
The Hamburger Icon was showing on large screen sizes because the CSS specificity that set `display: none;` was not specific enough.
=> Fix hamburger visible on large screen issue

app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js, app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
Addition to the collection milestone, this allows for `files` to be passed in as a sourceProperty to the registry file
=> Allow siphon to take multiple files

README.md, app-web/.dockerignore, app-web/Dockerfile, app-web/package.json
Add docker file and updated readme with instructions on how to use
- **package.json npm run dev script** has the `-H 0.0.0.0` paramater appended to it. This will allow for docker to run locally. The caveat is now local development on a windows machine is not possible. So sad.
=> Add configurations for docker, so we can develop in a consistent local env

app-web/__tests__/components/__snapshots__/CardFilterButton.test.js.snap, app-web/__tests__/pages/__snapshots__/Index.test.js.snap, app-web/package-lock.json, app-web/package.json, app-web/src/components/CardFilterButton/CardFilterButton.js, app-web/src/constants/ui.js, app-web/src/pages/index.js
Peter pointed out an issue that on smaller screens, when you click the card filter persona buttons, although it does actually trigger a filter, there is no visible change on the screen. This is because the bootstrap jumbotron takes up the entire view port and therefor leaves no space for a visual cue that the cards have changed. I added `react-scroll` to the party so that on click of those buttons, it scrolls to the container. 
Fixes #206
=> On click of the card filter button, it scrolls to card container

app-web/__mocks__/gray-matter.js, app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js
If you had front matter in a markdown file like 
```markdown
---
image: ./images/foo.png
---
```
This would not correctly render an image in the devhub because the path was relative to the github source. This has been corrected by adding another file transformer plugin.
Fixes #187 
** PLEASE NOTE ** this plugin has been authored and tested but not implemented. The reason for this is there are significant breaking changes within PR #213. The preferable thing to do is have that pr as well as this one merged and then a new pr created to implement this plugin.
=> Add new plugin to address relative image path issue in front matter

app-web/plugins/gatsby-source-github-all/__tests__/fetchSource.test.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/utils/fetchSource.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/githubFileTransformer.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/helpers.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
This file was getting over 500 lines of code. Broke it up into smaller files and made more of a convention of how authored source type routines should be made.
**NOTE this PR is not ready to merge**
It requires #212 to be merged and this PR rebased on top of it (the merge commit to master) since this branch is based off of #212
/bot-ignore-length
=> Refactor Siphons Fetch Source Github File into smaller files

app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceWeb.test.js, app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js, app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js, app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js, app-web/plugins/gatsby-source-github-all/utils/constants/sourceTypes.js, app-web/plugins/gatsby-source-github-all/utils/fetchSource.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js, app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
Added another 'sourceType' to siphon called `web`
A web source type and takes a `url` property as its sole `sourceProperties`
The url is unfurled and then created into a graphql node
- added source type `web `
- refactored source property validation routine https://github.com/bcgov/devhub-app-web/pull/214/files#diff-e9d28f0b4bea9f05787cd5359900ae47R125
- refactored unfurling an external url routine https://github.com/bcgov/devhub-app-web/pull/214/files#diff-e9d28f0b4bea9f05787cd5359900ae47R152
=> Add source type 'web' so that siphon can suck up information from a website

app-web/__fixtures__/redux-fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/src/store/reducers/siphon.js
> This is the front end implementation, the next PR will be the backend implementation for siphon which allows for registering multiple personas
Cards may have properties that are inside of an array eg
```yaml
name: foo
attributes:
personas: 
- bar
- baz
```
Prior to this PR, we could only filter by properties that were a single value. The `dotPropMatchesValue` fn has been modified to check for an array and match based on that if exists
#239
=> Move client side filtering to allow for fiiltering by a 1 to many relationship

app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js, app-web/src/utils/gatsby-remark-transform-path.js
Update Siphon to create collection nodes that reference their child siphon nodes.
In this pr, the fetch queue fn was refactored to create a list of 'collections'. This list is used looped over and sources fetched in a similar fashion leading to a backwards compatible way of fetching sources. 
The over all work required to convert siphon collections to a first class object is not entirely extensive but is best broken into smaller PRs. Therefor, this is the first of n successive prs.
Issue: #260
=> Siphon Collections as a first class object ( pr 1 of n)

app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js
This is part two of many parts in a series of small pull requests working to refactor siphon to create collection objects.
#265 
- refactor a few functions and added the createCollection fn with unit tests (not implemented yet though)
=> Siphon Collections as a First class object ( pr 2 of n)

app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
This is the final integration piece for the siphon collections. Collection nodes are now created with a link to each child siphon node.
nodes can now be queried like so
```graphql
query {
allDevhubSiphonCollection {
edges {
node {
id
name
childrenDevhubSiphon {
id
name
...siphonNodeProps
}
}
}
}
}
```
#265 #266 
Fixes #260
=> Siphon Collections as First Class Object (pr 3 of n)

app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/constants/registry.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js, app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
At this point registration configurations are not being validated, this pr is a slight refactor to the validation routine to allow for a predictable registry validation. 
- took a functional approach to the `validateSourceAgainstSchema` when refactoring, took out the common bits into `validateAgainstSchema` and use `validateSourceAgainstSchema` as a wrapper.
this is an effort for #258
=> Refactor Siphon validation Routine to ready for registration level validations

app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js
Siphon supports collection descriptions now
just add description to the collection registry confg
```yaml
- name: Foo
description: description here
sourceProperties: 
...
```
- Added unit tests for the schema validation routines as created from pr #274 
- Added more integration tests to siphon
Please notes this PR is for siphon only and doesn't not include any UI changes. 
#258
=> Add support for collection descriptions

app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js, app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/api.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
If a source collection is made with source type github. a collection description is now grabbed from the github repo api.
- get fetch queue was turned async to handle api calls from `getCollectionDescriptionBySourceType`
- added more unit tests
Issue #258 
Not ready for merge until #275 is merged and this rebased on top of master
=> Implicitly add github repository descriptions when source collection is github

docs/siphon.md
As of PR #287, the siphon/collection nodes have a meta data property
this has been documented
#257
=> Add documentation for siphon node changes

app-web/__tests__/components/Cards.test.js, app-web/__tests__/components/__snapshots__/Cards.test.js.snap, app-web/src/components/Cards/Cards.js, app-web/src/constants/ui.js
The number of cards that rendered within a collection in the devhub would sometimes show up in a less than ideal fashion. There maybe singled out cards that would wrap to a new row. This PR forces all cards to show up in atleast a group of three (if numCard >= 3);
- added a helper to calculate the ideal card limit for toggling
- added unit tests for said helper
Fixes #244
=> Fix card show more/less toggle button to render an appropriate number of cards in groups of 3

app-web/__fixtures__/redux-fixtures.js, app-web/__tests__/components/__snapshots__/Cards.test.js.snap, app-web/__tests__/pages/__snapshots__/Index.test.js.snap, app-web/__tests__/redux/siphonReducer.test.js, app-web/package-lock.json, app-web/plugins/gatsby-remark-path-transform/index.js, app-web/src/pages/index.js, app-web/src/store/reducers/siphon.js
#287 
This it the front end implementation of the ordering.
Note that the graphql query auto orders collections by the sort function
tried it. didn't work. There doesn't seem to be a sort function allowed on chiild gatsby nodes. The ordering is done withini the siphon reducer loadCollections action.
- used the new _metadata.position property of siphon nodes to create a order number based on the weight of the positions
```js
// eg position is an array of [collection {Number}, source {Number}, resource {Number}]
// weighting is based on the position of each element in the array. Left most are weighted heigher than 
// right most 
const position1 = [0, 2, 2];
const position2 = [1, 2, 2];
// after processing...
position1AfterWeight === '100.20.2'
position2AfterWeight === '200.30.3'
// not …
```
=> implement siphon node sorting by position

app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/constants/registry.js, app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/source-registry/registry.yml
integrated collection templates by type right now there are two different types
- default
- overview
they can be set in the registry with the following properties
```yaml
- name: foo
template: overview # if not provided defaults to 'default'
templateFile: [the template file name] # if templateFile and template are added, templateFile supersedes
```
#250
=> Integrate collection templates based on type

app-web/__tests__/redux/siphonReducer.test.js, app-web/src/pages/index.js, app-web/src/store/reducers/siphon.js
This is in an effort for #307, another PR will be made to first move all resource type queries to actual pages, this will make the search feature function better. In that effort variables are being renamed so that they are more sensible.
=> Rename siphon reducer state members

app-web/package-lock.json, app-web/package.json, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, docs/siphon.md
Updated the siphon node schema so that parent id is defined
, in addition `@bcgov/common-web-utils` package was updated
=> Siphon node now has references to parent collection

app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceWeb.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceWeb.test.js, app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js, app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js, app-web/plugins/gatsby-source-github-all/utils/constants/sourceTypes.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js, app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js, docs/registerRepo.md
When github resource types have a resource path their metadata was automatically unfurled based on the external resource. This is the same for web source types.
Now both are configurable so that any meta data in front matter (for github sourcetypes) or source properties (in web sourcetypes) that conflicts with the external unfurl is preserved
- added tests for new spec on the file transformer external unfurl plugin
- added integration tests for web source type
- updated docs
Fixes #299
=> Ability to override unfurl properties

app-web/package-lock.json, app-web/package.json, app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js, app-web/plugins/gatsby-source-github-all/__tests__/Store.test.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/Store.js, app-web/plugins/gatsby-source-github-all/utils/constants/registry.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js, docs/registerRepo.md
Page paths to resources were based on the github repo name, now there is a registry item `slug` configuration to allow for that to be changed. By default the collection `name` property is used as the slug in absence of the slug configuration
This is part one of two prs to fix #298 
Part two will involve providing slugs to resources as configuration instead of a generated id.
=> Allow registry items to have a slug property to control page path urls

app-web/__mocks__/slugify.js, app-web/__mocks__/valid-url.js, app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js, app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/constants/sourceGithub.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/githubFileTransformer.js, app-web/source-registry/registry.yml, docs/registerRepo.md
> This is PR 2 of 2 for #298 
__This is not to be merged until pr #318 is merged and this rebased ontop of it__
Markdown files support the `slug` property. In addition slug defaults to title and prints out a very clear warning message in the logs during name conflicts. 
Fixes #298
/bot-ignore-length
=> Markdown files can provide the `slug` front matter property

app-web/__fixtures__/plugin-fixtures.js, app-web/__tests__/components/__snapshots__/ActionRibbon.test.js.snap, app-web/__tests__/components/__snapshots__/Banner.test.js.snap, app-web/__tests__/components/__snapshots__/Card.test.js.snap, app-web/__tests__/components/__snapshots__/NavigationItem.test.js.snap, app-web/__tests__/components/__snapshots__/PrimaryFilter.test.js.snap, app-web/__tests__/gatsby-plugins/gatsby-remark-transform-path.test.js, app-web/__tests__/utils/utils.test.js, app-web/gatsby-config.js, app-web/package-lock.json, app-web/package.json, app-web/plugins/gatsby-remark-path-transform/__tests__/utils.test.js, app-web/plugins/gatsby-remark-path-transform/index.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.js, app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.module.css, app-web/src/components/UI/Link/Link.js, app-web/src/components/UI/PhaseBanner/PhaseBanner.js, app-web/src/utils/gatsby-remark-transform-path.js, docs/gatsby-custom-plugins/gatsby-remark-path-transform.md
Fixes #263 
This is done by maintaining a hash map of all gatsby page paths and the originating source that are related to a collection..
```js
collection._metadata.sourceLocations = [
[originalSource, pagePath],
]
```
The reason that it is in this data structure vs a **object literal** is that gatsby converts object literals into a graphql query object, and so the only way to grab the key/value pairs is to interface with graphql. 
Another benefit to this data structure is that it translates into a javascript `Map` object cleanly (which can be interfaced in a similar manner to a object literal).
- updates the gatsby path remark transform plugin
- the collection node now holds a hash map like object of all original resource paths and their gatsby page paths in the property …
=> Relative page links map to internal pages if they exist

app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/console.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/plugins.js, app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
When an external website either declared in a markdown file or by source type `web` gets unfurled. The metascraper library throws if there isn't any metadata. 
> I feel thats a poor design thing but oh well
This particular exception is handled now. Other errors (like 500) are still thrown and handled as they would before.
- fix the issue
- abstracted most console messages into a class that holds these messages in one neat place
- added a warning message if web source type unfurls lack meta data. 
Fixes #325
=> Fix siphon failing when trying to unfurl sites that have no metadata

app-web/src/components/Cards/Card/Card.module.css
I noticed smaller images in the cards aligned to the top of their container. This fix centers them.
=> fix a bug where smaller images wouldn't center in the cards

app-web/__tests__/components/SearchAwareLink.test.js, app-web/src/components/UI/Link/SearchAwareLink.js, app-web/src/components/UI/Link/index.js
This is a component that wraps the already in use `<Link>` component. Essentially it overrides the links behaviour of setting active class based on path matching. Instead it sets 'active' based on if query params match
__please note__ at this time the `<SearchAwareLink />` will only set active if it has one search parameter in its 'to' prop. multiple search param matching hasn't been implemented
This component is a refactor with the logic used in #344 which allows links to be active based on what searchs are currently in use. The primary navigiation filters are essentially a set of canned searches. #344 addressed a bug where the active link styling was not being applied because it wasn't aware of query params.
=> Add a react link component that sets active class based on search params

app-web/src/templates/SourceMarkdown.module.css
##Summary 
Set max width of markdown container to 800px for better readability.
=> Adjust max width of markdown page content container

app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/console.js, app-web/plugins/gatsby-source-github-all/utils/constants/registry.js, app-web/plugins/gatsby-source-github-all/utils/createNode.js, app-web/plugins/gatsby-source-github-all/utils/helpers.js, app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js, app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js, app-web/source-registry/__fixtures__/registry.yml
Added support for siphon to have collections point to a markdown file for overview content. The content is processed in the same way all siphon nodes are. 
This is not the implementation of the over view page. Only the base content!.
Fixes #246
=> Siphon Supports Collection Overview Content 

app-web/src/hoc/withResourceQuery.js, app-web/src/pages/index.js
The query is going to be used by the upcoming 'resource type' pages. I refactored it into its own component so that we can maintain the query in one place.
=> Abstract 'devhubSiphon' query into a reusable component

app-web/src/pages/index.js, app-web/src/templates/resourceType.js, app-web/src/utils/helpers.js
as pointed out by @jleach searching 'mobile' or 'signing' did not retrieve the mobile signing card as you would expect. This was found to be because searches were being conducted by partial tokenization eg __'*sign*'__.
I modified the search query to search in two ways, using partial and full matches and then combined the results to cast a larger net for relevant searches.
=> Refactor Search Function and combine partial/full searching to get better search results

app-web/source-registry/registry.yml
Changed the registry to source a non white version of the devex logo so that it the 'DevExchange' name is visible on the card.
=> update registry devex logo image to use the non white version

app-web/source-registry/registry.yml
Add rocketchat documentations to DevHub
- in collection `Community Enablers and Events` as Documentation
- including chat conventions and user instructions
=> Register rocketchat instructions

app-web/__tests__/components/GithubTemplateActions.test.js, app-web/__tests__/components/Link.test.js, app-web/__tests__/components/__snapshots__/Banner.test.js.snap, app-web/src/components/GithubTemplate/Actions/Actions.js, app-web/src/components/GithubTemplate/Navigation/NavItem.js, app-web/src/components/UI/Banner/Banner.js, app-web/src/components/UI/Banner/Banner.module.css, app-web/src/components/UI/Link/ChevronLink.js, app-web/src/components/UI/Link/Link.js, app-web/src/html.js, app-web/src/templates/SourceGithub_default.js, app-web/src/templates/SourceGithub_overview.js, app-web/src/templates/SourceMarkdown.module.css, app-web/src/utils/helpers.js
Add a component that has a link to the appropriate github repo issues page with precanned description and title
Fixes #470 
- restyled the main Link component so that its default 'look' is based on the design system. This reduced duplication within the code.
=> Feat/470 GitHub issues

app-web/__fixtures__/siphon-fixtures.js, app-web/__tests__/utils/selectors.test.js, app-web/src/utils/selectors.js
add general purpose reselect selectors to memoize and transform properties on base devhub gatsby nodes. This is in effort to statically render the pages #522
=> Add general purpose selectors to be used for static renderings

app-web/registry/authentication-and-authorization.json
Integrate the RH-SSO service definition content into the existing Wiki registry. Fixes #596.
=> Integrate the SSO service defenition

app-web/__fixtures__/eventbrite.js, app-web/gatsby-node.js, app-web/gatsby/sourceNodes.js, app-web/src/templates/TemplatePlaceholder.js
Fixes #604 
When a user tries to stand up the application without the eventbrite api key the app will not run. 
This has been addressed by:
- stubbing a fake eventbriteEvent node to prevent the page query from failing
- replacing the events page with a placeholder explaining whats going on.
=> Add logic to re route the eventbrite feature when not available

app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap, app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap, app-web/plugins/gatsby-source-github-all/utils/plugins.js, app-web/src/components/Cards/Card/Card.js, app-web/src/components/Cards/Card/index.js
Cards used to be truncated to two lines for some cards. This was found to be a bug within Siphon.
The bug was addressed and when there is only a description and no image for a card, lines are no longer truncated.
=> Prevent truncation of text on cards that have whitespace to hold the text

openshift/dc.yaml
Quick 1 line change in the dc.yaml file, creates 3 replicas on deployment instead of 2
=> Changing replica number from 2 to 3 for OpenShift 

app-web/__tests__/pages/__snapshots__/collections.test.js.snap, app-web/src/components/CollectionPreview/CollectionPreview.js, app-web/src/components/Home/index.js
-Linking the Topic header (on the home page) and the carousel topic titles to their respective pages
-Changed the "Hover:" CSS for the Topic header on the home page
-Added link in CollectionPreview.js for the "Collection title"
-Updated snapshot
Close #648
=> Linking the carousel topic titles out to their respective pages

app-web/__tests__/pages/Index.test.js, app-web/__tests__/pages/__snapshots__/Index.test.js.snap, app-web/src/pages/index.js
Changed the logic in the Index.js file (within pages folder) so that the cards are not shown by default on home page, while still maintaining the search functionality. Then updated the test files to match the new behaviour, and updated snapshots according.
close #649
=> Clearing up front page cards, without disturbing search functionality

app-web/gatsby/validators.js
This pr is an effort for the normalization of many source plugins. I'm taking a stab at doing preliminary normalization through the `createNodefields` function. Before that can be done we need a set of validators to run functions against when nodes are created. Hence this pr.
=> add validators functions to be used on node field creations

app-web/__tests__/utils/getFilesFromRegistry.test.js, app-web/gatsby/utils/githubRaw.js
The resolver used to only allow one topic from the registry to be bound the github raw node, now it correctly handles multiple topics
=> fix up github raw resolver to link multiple topics

app-web/__fixtures__/siphon-fixtures.js, app-web/gatsby-config.js, app-web/gatsby-node.js, app-web/gatsby/createResolvers.js, app-web/gatsby/onCreateNode.js, app-web/package-lock.json, app-web/package.json, app-web/src/components/Event/Logo.js, app-web/src/hoc/withResourceQuery.js, app-web/src/pages/collections.js, app-web/src/templates/events.js
Event pages break if events are private this was because:
- venues do not exist for nodes
- descriptions do not exist for nodes
- create node fields to normalize these fields
- comment out ux guild gatsby config plugin
Fixes #739
=> Fix Issue where events page breaks if events are private

app-web/__tests__/utils/getFilesFromRegistry.test.js, app-web/gatsby/utils/githubRaw.js
In prep for Devhub v3 migration, this pr is taking an other key feature of siphon and reproducing it using idiomatic Gatsby techniques.  This feature involves cascading any properties from the topic (such as personas/resource type) to the github raw node.
=> Add topic personas and resource type to github raw nodes

Jenkinsfile, matomo/Jenkinsfile
Closes #768.
We should not trigger a build for a component in a repo when changes pushed are not associated with it.
This PR contains modifications to the Jenkinsfiles for both devhub-app and Matomo to stop them from building unless changes to "their" files are contained in a triggering commit.
=> Only build component if there are changes associated with current Jenkinsfile

app-web/gatsby/onCreateNode.js
Eventbrite events now had the 'Event's resource type bound to it.
=> event brite has resource type events

.github/main.workflow, app-web/shell-scripts/unit-tests.sh
Closes #830 .
Our recent changes to our OpenShift build (enabling incremental builds) removed execution of unit tests.  This PR introduces a way that unit tests can be run using GitHub Actions.  Successful execution will show up as a "check" in GitHub.
=> Adding GitHub workflow to execute unit tests.

app-web/.s2i/bin/assemble, app-web/.s2i/bin/save-artifacts, app-web/shell-scripts/s2i-build-incremental.sh, openshift/templates/bc.yaml
The builder image that we are currently using in the cluster does not support incremental builds as-is.  This PR adds s2i scripts that will cause it to support incremental builds, with the goal of speeding up build performance in the cluster.
Also, this PR is adding a utility script to perform s2i build locally.
=> Adding s2i scripts to enable incremental builds

openshift/templates/dc.yaml
The site has been very slow to load as of late. After performing a Lighthouse audit, the audit recommended enabling text compression using `gzip` or `brotli`. Caddy has on-the-fly gzip built in as a directive and so I enabled that. 
- included the caddy file config map as apart of the deployment so that every deployment has its own caddy file
- boosted caddy resources to take into account requirements for on-the-fly gzipping
=> Improve site load performance by adding on the fly gzipping of assets with Caddy

app-web/__tests__/pages/Index.test.js, app-web/src/pages/index.js, app-web/src/utils/hooks.js
Added a few re-usable react hooks for searching rocket gate
- added a `useAuthenticated` which validates the authorization token
- added a `useRCSearch` hook to perform searches and return data in a memoized fashion
=> Rocket Chat search now based on an authenticated user

app-web/__tests__/components/ResourcePreview.test.js, app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap, app-web/src/components/Home/ResourcePreview.js, app-web/src/components/Search/SearchPills.js, app-web/src/components/Search/SearchSources.js, app-web/src/components/UI/Pill/index.js, app-web/src/pages/index.js
- Search results are no longer grouped by resource type but now by relevance. The resource type metadata can be seen above the results with their respecting result counts
- When clicked, the resource type pills now filter the results being shown according to the given resource type
- click on = filter, click off = all results back
- RocketChat Icon can now be seen even if not logged in, but when the user isnt logged in - it is faded
=> Sort search results by relevance, and show result count by resource type with interaction

app-web/blog/devhub.md
- Fixing the typo found in the About DevHub page
=> Fixing typo in devhub.md

app-web/package-lock.json, app-web/package.json, app-web/src/auth.js
Fixes #940 where bookmarking a search query would not work because the implicit auth redirect uri would ignore the query params
=> Update redirect uri to include search query

.pipeline/lib/deploy.js, app-web/__fixtures__/searchsources.js, app-web/__tests__/pages/Index.test.js, app-web/__tests__/utils/search.test.js, app-web/src/config.js, app-web/src/constants/api.js, app-web/src/constants/runtimeGraphqlQueries.js, app-web/src/pages/index.js, app-web/src/utils/hooks.js, app-web/src/utils/search.js, app-web/wrapWithProvider.js, openshift/templates/dc.yaml
As described by issue #907, we are leveraging search gate to perform our runtime graphql searches. This returns payloads from different search sources in a standard schema. 
This pr integrates search gate and modifies any infra code that referenced Rocketgate with Search gate
Reference repositories for the two can be found here
https://github.com/bcgov/searchgate
https://github.com/bcgov/rocketgate
fixes #907
=> Replace rocket gate apollo client with search gate

app-web/__tests__/components/__snapshots__/Search.test.js.snap, app-web/__tests__/components/__snapshots__/ToolsMenu.test.js.snap, app-web/__tests__/pages/__snapshots__/Index.test.js.snap, app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap, app-web/src/components/Home/ResourcePreview.js, app-web/src/components/Search/index.js, app-web/src/components/UI/Input/Input.js, app-web/src/utils/helpers.js
Instead of using placeholder, we are now using searching query from last time as value after click search(Intimate what other search engine is doing).
=> Cancel placeholder for search input and update snapshot

app-web/package-lock.json, app-web/package.json, app-web/src/components/DynamicSearchResults/index.js, app-web/src/components/Search/SearchSources.js
Based off of issue #899, we found it necessary to change the anchor links to the containers that contained external search results to a programmatic scroll.
- Integrated React Scroll
- Removed some old packages that weren't being used
Fixes #899 #941
=> Convert anchor links for search sources (github/rocketchat) to a programmatic scroll

app-web/src/templates/events.js
The events page is experiencing significant slowdowns. After some troubleshooting, we discovered that it was due to the sheer amount of 'event' cards that are rendered on the page. As a bandaid fix, we are removing historical events for now. #964 addresses displaying them on another page.
Fixes #948
=> Remove past events from the events page

app-web/__tests__/components/Masthead.test.js, app-web/src/components/Home/Masthead.js, app-web/src/pages/index.js
> Added an info box that provides the user with a tip that they can view more search results from github/rocketchat when logged in. Once acknowledged the message does not show up for the remainder of the application lifecycle. 
The alert will not show up again once it is close, and will only show if user is not logged in and search something
#939 
-
-
-
=> Add a alert for user to let then login to view more info

.gitignore, app-web/cypress/integration/DynamicTopic/index.spec.js, app-web/package-lock.json, app-web/src/components/GithubTemplate/Actions/Actions.js, app-web/src/components/TopicPreview/TopicPreview.js, app-web/src/pages/topic.js
Popular and Featured Topic pages would have a buggy 'create issue' link that would lead to a 404 page on github.  This has been resolved and some cypress tests were added to assert this.
=> fix bug where create issue link wouldn't work on dynamic pages

app-web/registry/information-and-application-security.json
Add the Platform Services documentation for teams to use to create secure, Zero Trust, networks.
- Add to information and application security index.
=> Add SecOps docs to index

app-web/__tests__/gatsby/validators.test.js, app-web/__tests__/pages/Index.test.js, app-web/__tests__/pages/topics.test.js, app-web/__tests__/utils/__snapshots__/selectors.test.js.snap, app-web/gatsby-config.js, app-web/gatsby/createPages.js, app-web/gatsby/createResolvers.js, app-web/gatsby/createSchemaCustomization.js, app-web/gatsby/onCreateNode.js, app-web/gatsby/utils/validators.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js, app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/src/hoc/Layout.js, app-web/src/hoc/withResourceQuery.js, app-web/src/pages/index.js, app-web/src/pages/topics.js, app-web/src/templates/SourceGithub_default.js, app-web/src/templates/SourceGithub_overview.js, app-web/src/templates/events.js, app-web/src/utils/selectors.js
The DevhubTopic node is one of the last remaining remnants of the monolithic plugin for devhub siphon
- removed dehubtopic and leveraged the topic registry file just the same as the journey registry. 
- updated tests
- improved site performance?
=> Deprecate DevhubTopic Node

app-web/topicRegistry/community-contributed.json
The repo `nr-document-generation-showcase` was changed to `document-generation-showcase` which was causing failures to build. 
@sheaphillips should we make the devhub fault tolerant to this type of issue?
=> Update nr repo name in registry

Caddyfile, app-web/gatsby/onCreatePage.js, app-web/src/pages/topic.js, openshift/templates/caddyfile.configmap.yaml, openshift/templates/dc.yaml
I found out that the dynamic topic page was not truly client side loading. This has been enabled so that page paths from `/topic/:topicType/:resource` can be parameterized. 
The reason for this change is an effort to fix the unknown css bug that affects the popular page on refresh. 
Fixes #1089
=> Make dynamic topic page client side loading

app-web/package-lock.json, app-web/plugins/gatsby-source-github-all/__tests__/fetchSource.test.js, app-web/plugins/gatsby-source-github-all/sourceNodes.js, app-web/plugins/gatsby-source-github-all/utils/fetchSource.js, app-web/src/hoc/withResourceQuery.js
the dev hub siphon source plugin was still getting GitHub resources. This code has been removed. This will greatly reduce the search index size.
=> chore: deprecate siphon getting github resources

app-web/topicRegistry/community-contributed.json
This should add the page, https://bcgov.github.io/ExchangeLabOps/Resident-Teams/README.html, to the Dev hub app.  I was not sure how to run the dev hub web app locally, so this change was *not* tested.
-
-
-
=> Added ExchangeLabOps markdown file to the dev hub docs page

scheduled.Jenkinsfile
Add a trigger to ignore postCommitHooks so that our scheduled build always runs
Fixes #1109
=> update  scheduled build

.github/workflows/nodejs.yml, app-web/package-lock.json, app-web/package.json
The infinite redirect issue is happening in Safari. I believe this is because safari seems to strip hash fragments occasionally 🤔 
the latest version of `@bcgov/common-web-utils` counts redirects and bases logic on that count instead of implicitly through existance of certain hash fragments.
=> install updated version of iam

app-web/__tests__/utils/algolia.test.js, app-web/src/utils/algolia.js
flatten the source node, now githubraw and other resources will have the same deep of index on algolia.
=> update flatten function

app-web/src/components/Journey/SubwayLine.js
The padding in mobile view was a bit too much. The padding was reduced for mobile views but kept the same for larger screens :fire:
Fixes #1115
=> Fixing journey map view

.jenkins/openshift/deploy-master.yaml, .jenkins/openshift/deploy-slave.yaml
Because gluster provisioning is off for new jenkins deployments in our pr based pipeline. this was a great opportunity to switch our jenkins to ephemeral.
=> Switch jenkins from persistant to ephemeral

app-web/gatsby-config.js, app-web/package-lock.json, app-web/package.json
Some users have been experiencing wildy incosistent 404 issues with the Devhub and it looks like it has been narrowed down to a hard-to-remove and long lived `sw.js` (service worker) file that is not being replaced. 
The removal of the service worker is necessary for these users to be able to experience the site correctly. 
The sw's primary function is to prefetch our page resources to make concurrent server requests snappy. This will be disabled and we will look to add the service worker when a sufficient amount of time has passed (I'm thinking about 2 monthes)
Fixes #1242
=> Add remove service worker pluginn

app-web/src/components/Search/SearchSources.js
Fixes issue #1248 
Changed the title of the github/rocketchat buttons to show correct text when hovered over
=> Changed Github/Rocketchat Icon Button titles

.github/actions/devhub-markdown-frontmatter-verify/jest.config.js
markdown action babel was transforming json files incorrectly. Oops!
=> Bug: fix regex for babel jest in markdown action

app-web/cypress/integration/Home/search.spec.js
For some reason the e2e cypress tests seem to be failing on github actions, while they work locally. 
The tests currently fail to fetch the journey and the topics filter pill, which were lately added as a feature to the devhub
=> Fix e2e Cypress tests

app-web/topicRegistry/developer-tools.json
Ref: #1379 
There is a hole in our pipeline flow that prevents forks from being built/deployed. This is a work around.
=> add resource-tuning-recommendations

app-web/src/pages/topics.js
Fixes issue #1323. 
Fix issue where images would not show on the cards on the topics page.
Edit the topic graphql query to include image field.
=> Fix topic cards to include images

app-web/topicRegistry/developer-tools.json
This adds the sysdigteams topic in support of this issue: https://github.com/BCDevOps/developer-experience/issues/797
- Just adding the sysdig teams developer user guide
=> Add sysdig-teams topic

.pipeline/lib/deploy.js, app-web/gatsby-config.js, app-web/src/components/Search/SearchGateResults.js, app-web/src/hoc/withResourceQuery.js, app-web/src/templates/events.js, docs/registry.md
Updates the Rocket.chat URL to `chat.developer.gov.bc.ca` from `chat.pathfinder.gov.bc.ca` across documentation, commented code, and live code.
- I've confirmed the new `CHAT_WEBHOOK_URL` fallback URL in `.pipeline/lib/deploy.js` returns the same response as the old URL. (62552dc)
- The commented URL referencing a particular message about the Meetup API works as expected with the new URL. (9740d32)
=> Update Rocket.chat URL to use chat.developer.bc.ca

web/topicRegistry/getting-started-on-the-devops-platform.json
Allow the [networkpolicy migration guide](https://github.com/bcgov/networkpolicy-migration-workshop) to be searchable on the devhub
=> add networkpolicy migration guide to registry file

web/topicRegistry/community-and-events.json, web/topicRegistry/getting-started-on-the-devops-platform.json
The devhub was pointing to an archived repo instead of the one where reggie is actively being developed!
=> update "Steps to Join Rocketchat" location to non-archived version

web/topicRegistry/community-and-events.json
Add community meetup doc to add to the events tile.
Address issue: https://github.com/bcgov/devhub-app-web/issues/1598
=> add community-meetup to events tile

web/journeys/cloud-pathfinder-onboarding.md
Updated text and removed old imgur link replacing it with versioned copy of image file.  The problem with imgur is people could be having a discussion thread over there about the image and we'd never know, whereas in github people can discuss in an issue which the team would immediately pick up.  Plus versioning and meaningful file names.
-
-
-
=> Removed image from imgur

CODEOWNERS, web/README.md
This PR fixes a typo, but it is mainly here for me to learn the process of deploying a new build of DevHub to OpenShift.
- Fix typo in `./web/README.md`
=> Fix typo in web/README.md

openshift/templates/web/bc.yaml, openshift/templates/web/dc.yaml
This pull request is an attempt to fix [this broken build](https://github.com/bcgov/devhub-app-web/runs/7868142345?check_suite_focus=true) which is failing with this error:
`error: failed to read input object (not a Template?): resource mapping not found for name: "devhub-app-web-bc-template" namespace: "" from "openshift/templates/web/bc.yaml": no matches for kind "Template" in version "v1"`
=> Update apiVersion in web/bc.yaml OpenShift template

web/topicRegistry/cloud-pathfinder.json
This PR re-adds the AWS Services page to DevHub. This page was retired in [Remove PS Team's migrated content from DevHub #2757](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2757) but it is not content that is available elsewhere yet. This page is referenced from the new `cloud.gov.bc.ca` landing page, which prompted me to check this out.
=> Revert retirement of AWS Services page

web/topicRegistry/community-and-events.json
Because BCDevExchange.org is being decommissioned, its product team has allowed their SSL certificate to expire this afternoon. Since we have a link to this site in our Community and Events topic registry, this causes an error when Gatsby tries to access that site to build a link card for it.
```
ERROR 
{ HTTPError: certificate has expired
at request.then (/Users/tykrys/code/devhub-app-web/web/node_modules/preq/index.js:246:19)
at tryCatcher (/Users/tykrys/code/devhub-app-web/web/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/tykrys/code/devhub-app-web/web/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/Users/tykrys/code/devhub-app-web/web/node_modules/bluebird/js/release/promise.js:604:18)
at …
```
=> Remove Community and Event topicRegistry reference to BCDevExchange.org

web/topicRegistry/community-contributed.json
Following user feedback, this PR removes DevHub pages relating to common services that have been retired.
- The DGEN API is now the [CDOGS](https://digital.gov.bc.ca/common-components/common-document-generation-service)
- The Messaging Service functionality is now a part of [CHES](https://digital.gov.bc.ca/common-components/common-hosted-email-service)
This pull request removes three "retired" landing pages and one page that still has content:
- https://developer.gov.bc.ca/Community-Contributed-Content/Messaging-Service-Developer-Guide
- https://developer.gov.bc.ca/Community-Contributed-Content/About-the-Messaging-Common-Service
- https://developer.gov.bc.ca/Community-Contributed-Content/NR-Document-Generation-Showcase
- https://developer.gov.bc.ca/Community-Contributed-Content/DGEN-Develo …
=> Remove old Common Services pages

web/src/assets/blog/devhub.md
[DEVEX-256](https://bcdevex.atlassian.net/browse/DEVEX-256) - update the link in the [github-repositories section on the Welcome to the DevHub page](https://developer.gov.bc.ca/aboutDevhub#github-repositories) to point to [https://github.com/bcgov](https://github.com/bcgov) vs [https://github.com/](https://github.com/).
This change was requested to make our GitHub organization easier to fine.
=> DEVEX-256 - Add link to BC Gov GitHub page from aboutDevHub page

web/topicRegistry/authentication-and-authorization.json
Updating references for some SSO cards to point to newer, external content.
- SSO Service definition now points to a page on digital.gov.bc.ca
-KeyCloak wiki now point to a new, correct location for the wiki
-
=> - updating links for SSO content per SSO PO request

.gitignore, web/src/components/UI/Link/ButtonLink.js, web/src/components/UI/Link/index.js, web/src/hoc/Layout.js
Adding a banner to all pages to point to new developer.goc.bc.ca MVP.
=> add-mvp-banner
