.gitignore
app-web/.env.example
app-web/.env.production.example
app-web/gatsby-config.js
app-web/src/__mocks__/@bcgov/common-web-utils.js
app-web/src/components/Auth/Login/Login.js
app-web/src/components/Auth/Login/Login.test.js
app-web/src/components/PrimaryHeader/PrimaryHeader.js
app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
app-web/src/components/PrimaryHeader/PrimaryHeader.test.js
app-web/src/components/PrimaryHeader/__snapshots__/PrimaryHeader.test.js.snap
app-web/src/constants/api.js
app-web/src/pages/Learn.test.js
app-web/src/setupTests.js

- sso base url now arriving from environment variable
- fixed some broken unit tests

Integrate authentication mechanics

---

app-web/src/components/Resource/Item/Item.js
app-web/src/components/Resource/Item/Item.module.css
app-web/src/components/Resource/Resource.js
app-web/src/components/Resource/Resource.module.css
app-web/src/mainNavigation.js
app-web/src/pages/__snapshots__/Index.test.js.snap

update content and styling for purposes of demonstration

Content update

---

jenkins/base/configuration/jobs/devhub-app-web/config.xml

> changed strategy from 1 to 2:
Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging
Discover each pull request twice. The first discovered revision corresponds to the result of merging with
the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging

update strategyId for github branch source strategy in config.xml

---

app-web/.babelrc
app-web/.s2i/bin/assemble
app-web/package.json
app-web/shell-scripts/unit-tests.sh
app-web/src/setupTests.js
openshift/bc.yaml

integrated unit testing into the build pipeline. The nodejs s2i assemble script now contains a call to run unit tests. The idea behind this is FAIL FAST. the build will kick out early if unit tests fail

Pipeline wip

---

README.md

Updated documentation
For [taiga task](https://taiga.pathfinder.gov.bc.ca/project/lukegonis-developergovbcca/us/73?milestone=17)

update readme with issue documentation

---

app-web/__mocks__/got.js
app-web/__mocks__/metascraper.js
app-web/__mocks__/valid-url.js
app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js
app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
app-web/plugins/gatsby-source-github-all/utils/plugins.js
app-web/plugins/gatsby-source-github-all/utils/transformer.js

As per #103, this PR contains those changes + updates to unit/integration tests.
- updated FileTransformer to run asyncronously
- updated all unit/integration tests to respect FileTransformer Changes
- Added unit tests for external unfurl plugin
- Attempted at improving the readability for some of the code

Implement Async Transformer and Update/Add Tests

---

app-web/package-lock.json
app-web/plugins/gatsby-source-github-all/utils/constants.js
app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
app-web/source-registry/registry.yml
docs/siphon.md

Just adding a new "component" source to the DevHub.

Adding "openshift components" (component type) and "DevHub" source  (repositories type).

---

app-web/__tests__/components/__snapshots__/PrimaryHeader.test.js.snap
app-web/src/components/Common/Banner.js
app-web/src/components/Common/Common.module.css
app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
app-web/src/components/UI/AppLogo/AppLogo.js
app-web/src/components/UI/AppLogo/AppLogo.module.css
app-web/src/constants/strings.js

Updated to Devhub from Developer's Hub
Updated the header logo to look like the one in our current version of the mockups
Also made the entire image/logo clickable (it navigates user to homepage)

Update Devhub Title

---

rmconfig.json

Add basic config file for repo mountie; this enables PR size limits.

Add repo mountie config

---

app-web/src/assets/styles/index.css
app-web/src/components/Cards/Card/Card.module.css
app-web/src/components/Cards/Cards.module.css
app-web/src/hoc/TemplateLayout.module.css
app-web/src/html.js
app-web/src/templates/SourceMarkdown.module.css

Added the bootstrap 4 global stylesheet via a cdn.
- bootstrap cdn added
- fixed any components/layouts that were broken from this adapation

Add Bootstrap and Update any styles that were broken

---

app-web/__tests__/components/__snapshots__/Card.test.js.snap
app-web/package-lock.json
app-web/package.json
app-web/src/components/Cards/Card/Card.module.css
app-web/src/components/Cards/Card/ComponentCard.js
app-web/src/components/Cards/Card/DefaultCard.js
app-web/src/components/Cards/Card/DocumentCard.js
app-web/src/components/Cards/Card/RepositoryCard.js
app-web/src/components/Cards/Card/SelfServiceCard.js
app-web/src/constants/ui.js
app-web/src/pages/index.js

added images to all card components
- added images to cards
- restyled cards so that images fit predictably in containers when they exist
- added truncation of description text incase it's over 5 lines

Add images to cards

---

app-web/__tests__/components/ActionRibbon.test.js
app-web/__tests__/components/MetadataRibbon.js
app-web/__tests__/components/Ribbon.test.js
app-web/__tests__/components/__snapshots__/ActionRibbon.test.js.snap
app-web/__tests__/components/__snapshots__/Card.test.js.snap
app-web/__tests__/components/__snapshots__/Ribbon.test.js.snap
app-web/src/components/Cards/Card/Card.module.css
app-web/src/components/Cards/Card/DefaultCard.js
app-web/src/components/Cards/Card/DocumentCard.js
app-web/src/components/Cards/Card/MetadataRibbon.js
app-web/src/components/Cards/Card/RepositoryCard.js
app-web/src/components/Cards/Card/SelfServiceCard.js
app-web/src/hoc/Card.js
app-web/src/store/reducers/features.js

for now this only contains resource type. I do know shea has a plan to add the 'persona' attributes. It should be easy enough to integrate personas into this ribbon

add metadata ribbon

---

app-web/src/components/Cards/Card/Card.module.css
app-web/src/hoc/Card.js

For Taiga ticket 603-enhance-page-view-styling. Minor updates to the front of card.

updated the fronts of the cards

---

app-web/package-lock.json
app-web/src/components/SourceNavigation/SourceNavigation.module.css
app-web/src/hoc/TemplateLayout.module.css
app-web/src/templates/SourceMarkdown.module.css

Added component page basic styling to headers and tables.

603 enhance page view styling  component page

---

docs/registerRepo.md
docs/registry.sample.yml

Update Siphon Docs for sourcing file/files in registry

---

docs/sourceCollections.md

Give examples using the `file` and `files` source props

Add more examples on how to config a collection in the source registry

---

app-web/src/pages/index.js
docs/sourceCollections.md

Updated the graphql query. Also fixed a minor issue in some docs.

Update index page to organize nodes by collection name

---

app-web/gatsby/createPages.js
app-web/src/templates/SourceGithubHTML.js
app-web/src/templates/SourceGithubMarkdown.js

Navigation within a created page was based on the source. This has been changed to be based on the collection

page navigation works against collection

---

docs/registerRepo.md

Update Documentation for using Inline Ignores in the Registry

---

app-web/src/hoc/GithubTemplateLayout.js

Hide page navigation if there are < 1 pages for a given collection

---

app-web/source-registry/registry.yml

fix persona attribute for open shift components registry item

---

docs/registerRepo.md

updated docs. There were errors in the ignores configuration example

Update regiserRepo docs

---

app-web/__tests__/components/__snapshots__/AppLogo.test.js.snap
app-web/src/assets/styles/index.css
app-web/src/components/PrimaryFilter/PrimaryFilter.module.css
app-web/src/components/UI/AppLogo/AppLogo.js
app-web/src/components/UI/AppLogo/AppLogo.module.css
app-web/src/html.js

- Updated header name to match standard
- Changed global font family to Noto Sans
-
Fixes #216

Fixed header branding/update font

---

docs/siphon.md

Update Siphon documentation

---

app-web/__tests__/components/__snapshots__/Cards.test.js.snap
app-web/src/components/Cards/Cards.js
app-web/src/components/PrimaryFilter/PrimaryFilter.js
app-web/src/constants/ui.js

Fixed most prop type errors that we were getting. There is on error found within `ComponentCard` that I can't seem to nail down

remove prop type error on PrimaryFilter

---

app-web/__tests__/components/CardFilterButton.test.js
app-web/__tests__/components/PrimaryFilter.test.js
app-web/__tests__/components/WelcomePanel.test.js
app-web/__tests__/components/__snapshots__/CardFilterButton.test.js.snap
app-web/__tests__/components/__snapshots__/PrimaryFilter.test.js.snap
app-web/__tests__/components/__snapshots__/WelcomePanel.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/gatsby-config.js
app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
app-web/src/components/UI/GovLogo/GovLogo.module.css
app-web/src/components/WelcomePanel/WelcomePanel.js
app-web/src/pages/index.js
app-web/src/pages/index.module.css

Isolated the welcome panel into its own component and updated tests so that there are no more proptype warning messages

Refactor Client Side

---

app-web/__tests__/components/__snapshots__/Layout.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/src/components/Dropmenu/Dropmenu.js
app-web/src/components/FilterMenu/FilterMenu.js
app-web/src/components/FilterMenu/FilterMenu.module.css
app-web/src/components/SecondaryFilter/SecondaryFilter.js
app-web/src/components/SecondaryFilter/SecondaryFilter.module.css
app-web/src/components/Sidebar/Sidebar.js
app-web/src/components/Sidebar/Sidebar.module.css
app-web/src/constants/featureflags.js
app-web/src/hoc/Layout.js
app-web/src/pages/index.js
app-web/src/pages/index.module.css
app-web/src/store/reducers/features.js

Fixes #231 
- Cleaned up in the index page

Client Side Refactorings #3

---

app-web/package-lock.json
app-web/package.json
app-web/src/templates/SourceGithubMarkdown.js
app-web/src/templates/SourceMarkdown.module.css

Added a markdown stylesheet so that the markdown pages look better

Adjust Markdown Styling

---

app-web/__tests__/components/__snapshots__/Layout.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/src/hoc/Layout.js
app-web/src/pages/index.js

The filter components were put into into the layout component but what the ended up doing was making the layout tied to the card filtering mechanism on the index page. Since there is potential for many different pages, this was removed to make the layout more usable.

Revert Filter Components into Index Page From Layout Component

---

README.md

Just adding a `-v` to the docker run instruction for dev.

add `-v` to docker run instruction

---

docs/siphon.md

update documentation for siphon collections
#267

update siphon docs for collections

---

app-web/Dockerfile

Change the Dockerfile to not use root and fix file permissions related to #268 
- Image uses `app` user now instead or root
- App is installed into '/home/app/'

Fix docker permissions

---

app-web/plugins/gatsby-remark-path-transform/index.js

Fix broken anchored header links

---

docs/registerRepo.md
docs/siphon.md
docs/sourceCollections.md

Documentation changes for marked issue
Issue #258

update docs to reflect changes to the collections schema

---

app-web/__tests__/components/__snapshots__/Cards.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/src/components/Cards/Cards.js
app-web/src/components/Cards/Cards.module.css
app-web/src/pages/index.js

Added collection descriptions to devhub.
Fixes #258

Devhub has collection/repo descriptions

---

app-web/__fixtures__/redux-fixtures.js
app-web/__tests__/components/__snapshots__/Cards.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/__tests__/redux/siphonReducer.test.js
app-web/package-lock.json
app-web/plugins/gatsby-remark-path-transform/index.js
app-web/source-registry/registry.yml
app-web/src/pages/index.js
app-web/src/store/reducers/siphon.js

Adding a new collection for Service Definitions, and the first of these for the gov OpenShift Container Service.
- mod to registry to create new collection and explicitly include the OpenShift service def and explicitly ignore service definition from the existing openshift-wiki collection
- related change is to openshift-wiki repo to add the md file containing the service definition content.

registry changes to set up a collection for service definitions

---

app-web/src/assets/styles/index.css
app-web/src/components/GithubTemplate/SidePanel/SidePanel.module.css
app-web/src/components/PrimaryFooter/PrimaryFooter.module.css

- on pages remove the side bar nav in print
- make background color white in print
- remove footer in print
Fixes #302

Make Print css optimizations

---

app-web/src/templates/SourceMarkdown.module.css

Changed the font colour for headings
-
-
-

Update Markdown header font colour

---

app-web/__tests__/components/Search.test.js
app-web/__tests__/components/__snapshots__/Search.test.js.snap
app-web/src/components/Search/Search.js

UI search bar component, created, tested but not implemented.
#307 
/bot-ignore-length

add Search component based on spec

---

jenkins/base/configuration/jobs/reggie-api/config.xml
jenkins/base/configuration/jobs/reggie-web/config.xml

add in jenkins config for reggie and reggie-web

---

app-web/__mocks__/gatsby-link.js
app-web/__tests__/components/ToolsMenu.test.js
app-web/src/components/Search/Search.js
app-web/src/pages/index.js

Improve tech debt for search feature

---

docs/registerRepo.md
docs/siphon.md
docs/sourceCollections.md

In prep for the the pr that will fix #246. Here is the docs explaining how to get collection pages running. 
Please note no implementation of collection pages exists only the backend structure supports it now.

Add docs for collection pages

---

app-web/__tests__/components/NameSpacedImg.test.js
app-web/__tests__/hoc/avatarUri.test.js
app-web/package-lock.json
app-web/package.json
app-web/src/components/UI/NameSpacedImg/NameSpacedImg.js
app-web/src/constants/ui.js
app-web/src/hoc/avatarUri.js

This is a follow up on PR #379 . That pr was closed as it included implementing these components. We are canning that for now since the cards are being redesigned. 
This pr just holds the components which can be used at a later time.
Fixes #396

Add ability to leverage react avatar using a uri

---

openshift/bc.yaml
openshift/dc.yaml

Add deadline seconds to build config
add ready seconds to deploy config

Modify deploy and build configs for requests and timeouts

---

app-web/src/components/Navbar/Navbar.js
app-web/src/components/PrimaryFooter/PrimaryFooter.js
app-web/src/constants/routes.js
app-web/src/constants/ui.js

Navigation leads to resource type pages

integrate routes into navigation

---

app-web/__tests__/components/__snapshots__/PrimaryFooter.test.js.snap
app-web/src/components/PrimaryFooter/PrimaryFooter.module.css
app-web/src/constants/routes.js
app-web/src/constants/ui.js

-Updated routes.js and ui.js files to add required links to DevHub footer
-Updated snapshot for unit tests
-
-
-
/bot-ignore-length

Style devhub footer

---

app-web/__fixtures__/siphon-fixtures.js
app-web/__tests__/components/Cards.test.js
app-web/__tests__/pages/Index.test.js
app-web/__tests__/redux/resourceActionCreators.test.js
app-web/__tests__/redux/resourceReducer.test.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/index.js
app-web/src/store/actions/resources.js
app-web/src/store/reducers/resources.js

Added collections to the redux state based on a spec
Also cleaned up some unused legacy constants
#397

Integrate collections in to reducer in prep for collections page view

---

app-web/__tests__/redux/selectors.test.js
app-web/src/store/selectors/collection.js
app-web/src/store/selectors/index.js
app-web/src/store/selectors/main.js
app-web/src/store/selectors/resources.js
app-web/src/templates/resourceType.js

Add selectors for collections in prep of Collections UI on homepage

Integrate Collections Selector

---

app-web/__fixtures__/siphon-fixtures.js
app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
app-web/src/components/Cards/Card/Card.js
app-web/src/components/Cards/Card/CardHeader.js
app-web/src/components/Cards/Card/index.js
app-web/src/components/CollectionPreview/CollectionPreview.js
app-web/src/components/UI/Link/ChevronLink.js
app-web/src/components/UI/Link/index.js
app-web/src/messages/index.js
app-web/src/pages/index.js
app-web/src/store/selectors/collection.js
app-web/theme.js

Created the Component for the collection preview to be used in the collection view page

Add Collection Preview Component

---

app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
app-web/source-registry/registry.yml

Updating the set of collections we have to be more " curated.
-
-
-

Updating curated collections

---

app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/__tests__/pages/collections.test.js
app-web/src/components/CollectionPreview/CollectionPreview.js
app-web/src/components/Page/CollectionsContainer.js
app-web/src/constants/routes.js
app-web/src/messages/index.js
app-web/src/pages/collections.js
app-web/src/templates/resourceType.js
app-web/src/utils/helpers.js

Collections page added minus search/filtering feature
#397

Add Collections Page 

---

app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
app-web/src/constants/routes.js

Reorder main navigation links

---

app-web/__tests__/components/Pill.test.js
app-web/src/components/UI/Pill/index.js

Add Pill component for usage in later Prs

Add Pill Component

---

app-web/source-registry/registry.yml

Remove slack page from registry

Remove slack page from registry

---

Jenkinsfile

set OCP-pipeline to version 0.0.6

---

app-web/source-registry/registry.yml

Add better key cloak logo from a more reliable source (github)

---

app-web/__tests__/components/__snapshots__/CollectionCard.test.js.snap
app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/src/components/Cards/Card/CardHeader.js
app-web/src/components/Cards/Card/Collection.js
app-web/src/components/Cards/Card/index.js
app-web/src/components/CollectionPreview/CollectionPreview.js
app-web/src/components/Home/CollectionsContainer.js
app-web/src/constants/ui.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/collections.js

#522
See prs #540  and #539 for reference.

Collections Page now loaded 100% statically

---

app-web/__fixtures__/siphon-fixtures.js
app-web/__tests__/components/FilterGroup.test.js
app-web/__tests__/components/__snapshots__/FilterGroup.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/__tests__/pages/resourceType.test.js
app-web/__tests__/selectors/selectors.test.js
app-web/gatsby/createPages.js
app-web/src/components/Filters/FilterGroup/FilterGroup.js
app-web/src/components/Filters/Filters.js
app-web/src/components/UI/Input/input.module.css
app-web/src/components/UI/NoResources/NoResources.js
app-web/src/constants/filterGroups.js
app-web/src/constants/search.js
app-web/src/constants/ui.js
app-web/src/hoc/withLocation.js
app-web/src/pages/index.js
app-web/src/templates/resourceType.js
app-web/src/utils/helpers.js

Converted the resource type pages to be loaded 100% static
- addition of a fantastic spec on searching/filtering features in tests
- filtering is now done via url query params
Fixes #522

Resource Template Pages now loaded 100% statically

---

app-web/source-registry/registry.yml

Synced up with master and now redoing the PR to add the dropdown menu component to DevHub.

Adding dropdown component

---

app-web/registry/information-and-application-security.json
app-web/source-registry/registry.yml

Adding some security-related content.
-
-
-
Fixes #456 and Fixes #457

adding security infographic and link to digital security site.

---

app-web/registry/agile-delivery-process.json

fixing error (unwanted "ignores" attribute) in registry file so new topic is processes and displayed properly.

Correct registry for "Agile Delivery" topic

---

app-web/registry/mobile-starter-kit.json

Integrate the mobile smarter kit repo by adding a new file to the registry. 
Fixes #595

Integrate mobile starter kit.

---

app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/registry/developer-tools.json
app-web/src/components/Cards/Card/index.js

Added a card that speaks on the Sizzy web tools
Fixes #507

Add sizzy card

---

app-web/__fixtures__/index.html

adding an index.html fixture file for integration testing of the @octokit/rest library with devhub. 
#606

create fixture html file for testing component preview

---

app-web/gatsby-config.js

Added to the search index to improve key word searches. I noticed you couldn't search for the title of a card which was annoying.

Update index to include source name

---

app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/src/components/Home/CollectionsContainer.js
app-web/src/constants/routes.js
app-web/src/messages/index.js

Changed (UI part of this task) from Collections to Topics and updated Unit Tests, still need to change the variable/data structure for Collections. 
-
-
-

Changed Collections to Topics and updated Unit Tests

---

app-web/gatsby-config.js
app-web/src/hoc/Layout.js
package-lock.json

Fix for the Nav issues on EI 11, using <script src="https://cdn.polyfill.io/v2/polyfill.min.js" /> (with helmet tags) in the layout.js file
-
-
-

Nav fix for EI 11

---

app-web/registry/getting-started-on-the-devops-platform.json

Added a new item to the registry in regards to 12 factor apps and progressive web apps
Fixes #635

add resource

---

app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/src/components/CardCarousel/CardCarousel.js
app-web/src/components/Cards/Container.js
app-web/src/components/GithubTemplate/common.js
app-web/src/components/Home/Masthead.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/components/Page/CardsContainer.js
app-web/src/components/Page/FilterMenu.js
app-web/src/constants/designTokens.js
app-web/src/constants/styleTokens.js
app-web/src/constants/ui.js
app-web/src/templates/SourceGithub_default.js
app-web/src/templates/SourceGithub_overview.js
app-web/src/templates/events.js
app-web/theme.js
docs/designTokens.md

Design Tokens are a way to maintain consistency among styles between components. Common styles are abstracted away into a constants file and used as template strings within the css-in-js components.
In addition I wrote up a quick doc explaining Design Tokens and how to use em'
This is in prep for #617

Begin integration of design tokens for better UI layout control

---

app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/src/components/Cards/Card/index.js

Just a one line CSS addition in the index.js file for the Card component

CSS fix for IE 11 text overflow on cards

---

app-web/src/components/Cards/Card/Card.js
app-web/src/components/Cards/Card/index.js
app-web/src/components/GithubTemplate/Navigation/NavGroup.js
app-web/src/components/GithubTemplate/Navigation/NavItem.js
app-web/src/components/GithubTemplate/Navigation/Navigation.js
app-web/src/constants/designTokens.js
app-web/src/templates/SourceGithub_overview.js
app-web/theme.js

As per designs from issue #617 
Fixes #617

Redeseign topic/collections view

---

app-web/__tests__/utils/helpers.test.js
app-web/plugins/gatsby-source-github-all/utils/plugins.js
app-web/registry/featured-cards.json
app-web/src/components/Home/CollectionsContainer.js
app-web/src/constants/topics.js
app-web/src/hoc/withResourceQuery.js
app-web/src/utils/helpers.js

- Creating Featured Cards topic
- Placing it at the top of the homepage
- Fixing the multiple resource slug issue
- updating tests accordingly
close #656

Creating Featured Cards topic

---

app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/__tests__/pages/resourceType.test.js
app-web/registry/developer-tools.json
app-web/registry/featured-cards.json
app-web/src/templates/resourceType.js

-Removed duplicate cards
-Fixed card duplication bug when searching
-Created a test to check for this behaviour
-Update snapshot
- For future reference: Resources in many collections will only be shown in one of their many contexts on the 'Tools', 'Components' and 'Documentation' pages
close #665

Removing duplicate cards and fixing duplication bug 

---

app-web/blog/clean-coding.md
app-web/plugins/gatsby-source-github-all/utils/registryHelpers.js
app-web/registry/authentication-and-authorization.json
app-web/registry/community-enablers-and-events.json
app-web/registry/design-system.json
app-web/registry/featured-cards.json

Add repos to registry files

---

app-web/src/components/GithubTemplate/Navigation/NavGroup.js
app-web/src/components/GithubTemplate/Navigation/Navigation.js
app-web/src/components/UI/ResourceTypeIcon/index.js
app-web/src/constants/ui.js
app-web/src/templates/SourceGithub_default.js

-Adding Event resource type
-Adding Eventbrite events to the sidebar of the Community Enablers and Events topic

Adding Event resource type and eventbrite events to Topic sidebar

---

app-web/__tests__/components/__snapshots__/NavigationItems.test.js.snap
app-web/__tests__/components/__snapshots__/PrimaryFooter.test.js.snap
app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/src/components/NavigationItems/NavigationItems.js

changed position of devex logo in footer
-
-
-
Fixes #619

changed position of devex logo in footer

---

app-web/__fixtures__/siphon-fixtures.js
app-web/__tests__/pages/collections.test.js
app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js
app-web/registry/community-and-events.json
app-web/src/constants/topics.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/collections.js
app-web/src/templates/SourceGithub_default.js

-Creating Community and Events Topic
-Updating resource types to match content on this topic
- Adding eventbrite Events to the topic carousel
close #658

Creating 'Community and Events' Topic and adding eventbrite events into its carousel

---

app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/src/components/CollectionPreview/CollectionPreview.js
app-web/src/components/Page/Main.js
app-web/src/templates/events.js

- Creating carousel on events page
- returning topic carousels to left align
- Updating snapshots
close #659

Creating carousel on events page and returning topic carousels to left align 

---

app-web/__tests__/utils/helpers.test.js
app-web/registry/featured-resources.json
app-web/src/constants/topics.js
app-web/src/utils/helpers.js

-Rename the topic
-update tests accordingly
close #684

Renaming featured cards topic

---

app-web/__fixtures__/siphon-fixtures.js
app-web/__tests__/pages/__snapshots__/collections.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/gatsby-node.js
app-web/src/components/CardCarousel/CardCarousel.js
app-web/src/components/Cards/Card/Card.js
app-web/src/components/Cards/Card/index.js
app-web/src/components/Event/index.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/collections.js
app-web/src/templates/events.js

- Redesign event page
- Redesign event card when its an eventbrite event
- updating tests and snapshots
- bit of refactoring on the eventbrite siphon

Redesigning event page and cards

---

app-web/registry/authentication-and-authorization.json

add in keycloak wiki. test if a github wiki source show up.
-
-
-

added github wiki as a github source

---

app-web/gatsby-config.js
app-web/package-lock.json
app-web/package.json
app-web/registry/data-and-apis.json
app-web/registry/featured-resources.json

Based off of #702 this pr was made so we can kick of a deployment to get these changes in prod
- added `gatsby-remark-emoji` so that : github : emoji dsl shows up in the pages
@ll911 thanks for the contribution :fire:
closes #717 #702

Content - Topic Data and Apis'

---

app-web/src/constants/routes.js

Search page was breaking when event came up as results, quick fix.

Fixing Search bug, that was happening when events came up as results

---

app-web/registry/getting-started-on-the-devops-platform.json

Added missing OpenShift network reference markdown file.
Closes #683

Adding OCP networking reference.

---

app-web/gatsby-config.js

re enable meetup plugin for ux guild

---

app-web/__tests__/utils/helpers.test.js
app-web/registry/getting-started-on-the-devops-platform.json
app-web/src/components/Home/CollectionsContainer.js
app-web/src/constants/topics.js
app-web/src/hoc/withResourceQuery.js
app-web/src/utils/helpers.js

-Adding resources to registry
-Adding topic to home page so it can easily be found

Adding more introductory OpenShift materials for those waiting to take the OpenShift 101

---

app-web/gatsby/onCreateNode.js

- Adding node fields to MarkdownRemark Nodes
- making sure they have decent default/fallback values

Adding node fields to MarkdownRemark Nodes

---

.yo-rc.json
matomo/.pipeline/lib/config.js
matomo/.pipeline/lib/deploy.js
matomo/Jenkinsfile
matomo/openshift/matomo/matomo-deploy.json

Dynamic dev deployment for Matomo

---

app-web/registry/authentication-and-authorization.json

remove broken link in registry

---

.jenkins/docker/contrib/jenkins/configuration/jobs/realm-o-matic/config.xml

update realm-o-matic job to not trigger builds on forked prs

---

app-web/__fixtures__/siphon-fixtures.js
app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
app-web/gatsby-config.js
app-web/gatsby/onCreateNode.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/index.js
app-web/src/templates/events.js
app-web/src/utils/selectors.js

Integrate resource type via fields

---

app-web/gatsby-config.js
app-web/gatsby/onCreateNode.js
app-web/gatsby/utils/githubRaw.js

Position between siphon and github raw nodes now perserved as a node field
-
-
-

add position to fields and map topics to siphon nodes

---

app-web/registry/community-and-events.json

Adding RedHat Event

---

app-web/registry/community-and-events.json

- Changing registry
close #632

Fixing Typo in Devops Commons Card

---

app-web/.env.production.example

add meetup api key to .env.example

---

app-web/.env.production.example
app-web/package-lock.json
app-web/package.json
openshift/templates/matomo.secret.yaml

add matomo api secret

---

app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/src/components/Home/Masthead.js
app-web/src/components/Page/CardsContainer.js
app-web/src/components/Search/SearchPills.js
app-web/src/pages/index.js
app-web/src/templates/resourceType.js

- when searching on the home page, there is now a pill box to show the total number of results

Search Result Total PillBox

---

app-web/.env.production.example
app-web/.eslintrc
app-web/gatsby-config.js
app-web/gatsby/createResolvers.js
app-web/gatsby/onCreateNode.js
app-web/gatsby/utils/validators.js
app-web/package-lock.json
app-web/package.json
openshift/templates/bc.yaml

Bind matomo page hits to github raw/web nodes

---

app-web/registry/community-contributed.json

Based off of pr #438 this is the pr with the registry item in the new format.

add location services guide

---

app-web/src/components/ComponentPreview/ComponentPreview.js

Quick fix for a bug with component previews

Fix a bug where markdown previews were not working

---

app-web/registry/community-and-events.json

Add redhat security symposium event

---

app-web/__tests__/components/__snapshots__/PrimaryHeader.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/registry/featured-resources.json
app-web/registry/getting-started-on-the-devops-platform.json
app-web/src/components/Navbar/Navbar.js
app-web/src/components/Navbar/Navbar.module.css
app-web/src/components/PrimaryHeader/PrimaryHeader.js
app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
app-web/src/hoc/Layout.js

Add a documize card to featured resources and getting started on the devops platform
- add a fix for the ui bug that would display the login button in mobile view
Fixes #862

Add documize

---

app-web/src/auth.js

Fixes a bug where the implicit auth manager redirects the user to home and doesn't respect their entry pointn

fix a bug where auth doesn't respect redirects

---

app-web/__tests__/pages/Index.test.js
app-web/gatsby-config.js
app-web/gatsby/onCreateNode.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/index.js
app-web/src/utils/helpers.js

- creating topicName field for MarkdownRemark nodes
- Adding markdown remark nodes to the withResourceQuery query so that they show up in search results
- Indexing markdown remark nodes in search index with topicName field
- Adding topicName field to eventbrite events and meetup events in the search index
close #880

Adding to search index and resource index for search

---

app-web/src/components/RocketChatResults/RocketChatItem.js
app-web/src/utils/search.js

format rocket chat date time

---

app-web/gatsby-config.js
app-web/gatsby/createPages.js
app-web/gatsby/sourceNodes.js
app-web/registry/community-and-events.json
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/index.js
app-web/src/templates/events.js

-Commenting out code involving meetup
-Adding meetup ups to the registry as sourceType "web"

Meetup Depreciation 

---

app-web/src/components/Home/Masthead.js
app-web/src/components/Page/CardsContainer.js

-Fixing empty search string bug by adding extra checks when displaying the search result pill

Fixing bug where search result pill would show if the search string was full of blank characters

---

app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/src/components/Home/Masthead.js

- Just creating a div to align the icon beside the search result pill

Align rocket chat icon beside the search result pill

---

app-web/.env.production.example
app-web/src/utils/hooks.js

search gate only shows results when authenticated

gate search gate with auth

---

app-web/src/components/Home/ResourcePreview.js

return nothing if there is no search result when push to pill array

hide a pill for '0 search results'

---

app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/src/components/Home/Masthead.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/utils/helpers.js

delete the pill shows all result under search bar, add total search number in All search result pill
#903

move result number to All search result pill

---

README.md
app-web/.storybook/addons.js
app-web/.storybook/config.js
app-web/.storybook/webpack.config.js
app-web/__tests__/components/__snapshots__/Banner.test.js.snap
app-web/__tests__/components/__snapshots__/PopularTopic.test.js.snap
app-web/__tests__/components/__snapshots__/PrimaryFooter.test.js.snap
app-web/__tests__/components/__snapshots__/Search.test.js.snap
app-web/__tests__/components/__snapshots__/ToolsMenu.test.js.snap
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/package-lock.json
app-web/package.json
app-web/src/components/Card/Card.js
app-web/src/components/Card/CardHeader.js
app-web/src/components/Card/index.js
app-web/src/components/Cards/Card/Card.js
app-web/src/components/Cards/Card/index.js
app-web/src/components/UI/Button/Button.js
app-web/stories/index.stories.js
app-web/stories/theme.js
app-web/theme.js

As described above, the card component has been greatly decomplicated*. It is now a set of composable sub-components. 
I also added storybook js to demonstrate/document the usage of these sub-components

Refactor Card Component to allow for dynamic headers/body and add storybook

---

app-web/__tests__/components/CardCarousel.test.js
app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap
app-web/__tests__/components/__snapshots__/PopularTopic.test.js.snap
app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/src/components/Card/Card.js
app-web/src/components/CardCarousel/CardCarousel.js
app-web/src/components/Cards/Card/Card.js
app-web/src/components/DynamicSearchResults/GithubCardHeader.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/components/Page/CardsContainer.js
app-web/src/components/TopicPreview/TopicPreview.js
app-web/src/pages/index.js
app-web/src/templates/events.js
app-web/src/utils/hooks.js
app-web/stories/index.stories.js

Based on the work from PR #959 , this PR will transition all cards to the refactored card component.

Integrate refactored Card Component

---

app-web/__tests__/utils/helpers.test.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/utils/helpers.js

We now can toggle multi pills and shows results based on what pill is selected

Imp/toggle pill#938

---

app-web/registry/authentication-and-authorization.json
app-web/registry/community-and-events.json
app-web/registry/developer-toy-box.json
app-web/registry/getting-started-on-the-devops-platform.json
docs/registry.md

- Generic content clean up task
- Also addressed some broken image links
Fixes #989

Remove old/irrelevant content from registry

---

openshift/templates/bc.yaml

Testing if this will speed up build execution. We were having issues that some builds would take over 20 minutes to run...
#968

Modify build config run policy

---

app-web/src/components/Search/index.js

add useeffect to change state if query is empty
fixed#992

fix bug for search input bar

---

app-web/gatsby/createPages.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/templates/events.js
app-web/src/templates/pastEvents.js

A new page to show all past events
fixed #964

 historical event page

---

app-web/__fixtures__/searchsources.js
app-web/__tests__/components/__snapshots__/PopularTopic.test.js.snap
app-web/__tests__/pages/Index.test.js
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/src/components/Card/index.js
app-web/src/components/DynamicSearchResults/GithubIssueCardHeader.js
app-web/src/constants/search.js
app-web/src/pages/index.js
app-web/src/pages/sitemap.js
app-web/src/utils/search.js

Github repos were not showing up during a search.
- this was found to be an issue with devhub 'cutting' off search results to short...because repos are always at the end of the results list from searchgate
fixes #976

Fix issue where no repos were showing in search results

---

.jenkins/openshift/deploy-slave.yaml
.pipeline/npxw
.pipeline/package-lock.json
.pipeline/package.json
Jenkinsfile
app-web/src/components/GithubTemplate/Actions/Actions.js
app-web/src/templates/StandAlone_GitHubRaw.js

Integrate github deployments api with our jenkins file. In addition, I addressed the no 'link' bug as found in issue #999 .
Fixes #497

Update Jenkinsfile with deployments api scripts

---

docs/disasterRecoverInstructions.md

add a instruction of how to redeploy devhub if something really bad happens

add a md file

---

Jenkinsfile

Using the Jenkinsfile linter I found no lint issues that would cause the failure. I've simplified the Jenkinsfile post script to troubleshoot. 
Fixes #1003

Attempting to fix Jenkinsfile post script issue

---

app-web/registry/developer-tools.json

basically what the title says - i added an entry in developer-tools.json to a readme file for the BCGov instance of artifactory!

added artifactory document to developer-tools.json

---

app-web/__tests__/components/GithubTemplateActions.test.js
app-web/__tests__/components/__snapshots__/PopularTopic.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/package-lock.json
app-web/src/components/Card/index.js
app-web/src/components/Journey/JourneyMap.js
app-web/src/components/Journey/JunctionList.js
app-web/src/components/Journey/Legend.js
app-web/src/components/Journey/SubwayLine.js
app-web/src/components/Journey/index.js
app-web/src/components/TopicPreview/TopicPreview.js
app-web/src/components/UI/ResourceTypeIcon/index.js
app-web/src/constants/ui.js
app-web/src/pages/index.js
app-web/stories/journey.stories.js
app-web/theme.js

This PR completes the work from #1035 and introduces the journey ui component. This has not been integrated yet. It has been tested in storybook however

Journey UI Component

---

.jenkins/docker/contrib/jenkins/configuration/jobs/docugate/config.xml
.yo-rc.json

Add Docugate job to Jenkins

---

Jenkinsfile
app-web/gatsby-config.js
app-web/gatsby/onCreateNode.js
app-web/gatsby/utils/githubRaw.js
app-web/registry/getting-started-as-a-developer.json
app-web/src/components/GithubTemplate/common.js
app-web/src/hoc/withResourceQuery.js
app-web/src/templates/StandAlone_GitHubRaw.js
app-web/src/templates/pastEvents.js

Based off the content found at https://github.com/devhub-resources/blob/getting-started-as-developer-topic
This adds that content plus a few bug fixes
- page only resources enabled via the frontmatter field `pageOnly: true`
- fixed a bug in the github raw resolver function

Add Developer Guide Topic to Devhub

---

openshift/templates/dc.yaml

update dc requests

---

app-web/package-lock.json

Upgrade packages with `npm audit fix`

upgrade vulnerabilities

---

app-web/gatsby/onCreateNode.js

image frontmatter fields would not render images if they were a relative path. This has been resolved

Fix an issue where local images would not render in frontmatter

---

docs/registry.md

add journey docs

---

.jenkins/.pipeline/lib/config.js
.jenkins/docker/contrib/jenkins/configuration/jobs/searchgate/config.xml
.yo-rc.json

We need a Jenkins job in order to build and deploy the new search gate component.  This PR contains the job definition.

creating new jenkins job for searchgate

---

app-web/topicRegistry/information-and-application-security.json

Added the markdown files that are part of Developer Guide to Network Security in platform-services repo to be included in the search index.

Updated information-and-application-security.json

---

scheduled.Jenkinsfile

fix curl request

---

scheduled.Jenkinsfile

update jenkins file

---

app-web/gatsby/onCreateNode.js
app-web/journeyRegistry/agile-delivery-process.json
app-web/journeys/agile-delivery-process.md
app-web/src/components/Home/JourneyContainer.js
app-web/src/components/Journey/JourneyMap.js
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/index.js
app-web/src/pages/journeys.js

Integrate topic into journey.
Only 'agile process' now,

add agile topic page into journey

---

app-web/src/pages/journeys.js

add entry page link to the journey page title.

missing journey page link

---

.pipeline/lib/deploy.js

add chat url

---

.pipeline/lib/deploy.js
.pipeline/utils/index.js

Rocket chat method was done broken and needed addressing.

fix issue with post rocket chat method

---

.pipeline/npmw

hopefully last troubleshooting step to fix jenkins scheduled builds

enforce using specific node version

---

app-web/__fixtures__/nodes.js
app-web/__tests__/pages/events.test.js
app-web/__tests__/pages/pastEvents.test.js
app-web/gatsby/createPages.js
app-web/gatsby/resolvers/devhubTopic.js
app-web/src/components/Card/Card.js
app-web/src/components/Card/CardsInColumns.js
app-web/src/components/Home/ResourcePreview.js
app-web/src/templates/events.js
app-web/src/templates/pastEvents.js

Address code smells from code climate

---

app-web/topicRegistry/information-and-application-security.json
app-web/topicRegistry/platform-security.json

Move platform security related content into its own topic so that it can be broadened over time.
- Create new topic

Create platform security topic

---

app-web/topicRegistry/developer-tools.json

updated developer-tools.json to reflect new location of artifactory docs

---

app-web/src/components/Home/Masthead.js
app-web/src/components/Search/SearchSources.js

quick fix for icon UI delay show up issue

Fix search source icons flicker

---

app-web/src/components/Search/SearchSources.js
app-web/src/components/UI/Button/Button.js
app-web/src/constants/search.js

Search resrouce code smells

---

app-web/src/components/TopicPreview/TableofContents.js

Based on Shea's suggestion, use right arrow instead on down arrow

use right arrow instead of down arrow

---

docs/registry.md

add some description for label and tag format for markdown frontmatter

documentation about label and tags

---

app-web/gatsby-config.js
app-web/package-lock.json
app-web/package.json
app-web/src/components/Journey/JourneyMap.js
app-web/src/components/SEO/SEO.js
app-web/src/hoc/Layout.js
app-web/src/templates/SourceGithub_default.js
app-web/src/templates/SourceGithub_overview.js
app-web/src/templates/StandAlone_GitHubRaw.js

make our sites more discoverable by search engines.

Add github sources' title as title with helmet

---

app-web/__tests__/gatsby/getFilesFromRegistry.test.js
app-web/__tests__/pages/Index.test.js
app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
app-web/plugins/gatsby-source-github-all/__tests__/registryHelpers.js
app-web/src/pages/index.js

Fix a little bit code that code climate point out.

Code quality improvement

---

app-web/topicRegistry/community-contributed.json

I refactored the ExchangeLabOps page.  As a result the linked file changed places.
-
-
-

Changed the file location

---

.github/workflows/nodejs.yml
app-web/package-lock.json
app-web/package.json

update common web utils

---

app-web/topicRegistry/developer-tools.json

remove artifcatory docs as a quick fix for issue #1161

remove artifactory docs

---

app-web/journeyRegistry/getting-started-as-a-developer.json
app-web/topicRegistry/information-and-application-security.json
app-web/topicRegistry/platform-security.json

Updated information security search index to include readme from BC-Policy-Framework-For-GitHub repo 
and added a the Policy Framework as a stop on the Developer Journey on the DevHub main page.
-
-
-

Included GitHub Policy Framework in search index and in Developer Journey

---

app-web/journeyRegistry/getting-started-as-a-developer.json
app-web/topicRegistry/information-and-application-security.json
app-web/topicRegistry/platform-security.json

Reverts bcgov/devhub-app-web#1166

Revert "Included GitHub Policy Framework in search index and in Developer Journey"

---

app-web/journeyRegistry/getting-started-as-a-developer.json
app-web/topicRegistry/information-and-application-security.json
app-web/topicRegistry/platform-security.json

Reverting the revert from pr #1168

Add content from #1166

---

.pipeline/lib/deploy.js

Update deployment creation for prs to include log url so we can reference the deployment url in the pr feed.

add log url to deployment creation"

---

app-web/__tests__/components/__snapshots__/PopularTopic.test.js.snap
app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/gatsby/onCreateNode.js
app-web/gatsby/resolvers/devhubTopic.js
app-web/src/components/Card/Card.js
app-web/src/components/Card/CardsInColumns.js
app-web/src/components/Card/index.js
app-web/src/components/Journey/JourneyMap.js
app-web/src/components/Journey/SubwayLine.js
app-web/src/components/Journey/index.js
app-web/src/templates/events.js
app-web/topicRegistry/community-and-events.json
openshift/templates/caddyfile.configmap.yaml

I'm Addressing various small issues identified in our issue backlog. Things that were 5-10minute tasks.
Fixes #1180 #1181 #1176 #1174

Chore Tasks for UI/UX bugs

---

app-web/topicRegistry/platform-security.json

Added Developer Workshop content to search index

Added Developer Workshop content to search index

---

README.md
app-web/__tests__/components/Masthead.test.js
app-web/__tests__/components/__snapshots__/404.test.js.snap
app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
app-web/__tests__/hoc/__snapshots__/LayoutComponent.test.js.snap
app-web/__tests__/pages/Index.test.js
app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/gatsby-config.js
app-web/package-lock.json
app-web/package.json
app-web/src/AuthContext.js
app-web/src/assets/blog/devhub.md
app-web/src/auth.js
app-web/src/components/Auth/Login/index.js
app-web/src/components/Home/Masthead.js
app-web/src/components/Navbar/Navbar.js
app-web/src/components/PrimaryHeader/PrimaryHeader.js
app-web/src/components/Search/SearchSources.js
app-web/src/hoc/Layout.js
app-web/src/hoc/withLocation.js
app-web/src/pages/index.js
app-web/src/utils/hooks.js
docs/README.md
docs/authentication.md

Hotfix for some UX issues that have been found
- fixed the broken images in the devhub about page
- fixed the redirect uri for logging in being stuck to the entry point into the devhub
- removed the offline plugin
Fixes #1190

fix several ux bugs

---

app-web/topicRegistry/developer-tools.json

just what it says on the tin :)

added artifactory documentation after gatsby fix

---

README.md

Minor proposal on line 62.
- There is no notable changes proposed

Minor proposal on line 62

---

app-web/topicRegistry/getting-started-on-the-devops-platform.json

add OCPStorageServices.md link

---

app-web/__tests__/components/__snapshots__/404.test.js.snap
app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
app-web/__tests__/hoc/__snapshots__/LayoutComponent.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/src/components/Auth/Login/index.js
app-web/src/components/Navbar/Navbar.js

Fixes #1193.
Just changed the logout button to look like a link so that is more differentiable from the login button

1193: (imp) Update logout button look and feel

---

CODEOWNERS

For issue #1214 
Created code owners' file for the dev-hub project.

Code Owners file

---

.github/workflows/cypress.yml
app-web/cypress/integration/Home/search.spec.js

Added a test to ensure you could bookmark a search and have it work when loaded. In addition I increased the timeout for our cypress e2e github action since it seemed to be failing because the server could take over a minute to load.

Add addition e2e test for algolia

---

app-web/__tests__/pages/__snapshots__/Index.test.js.snap
app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
app-web/cypress/integration/Home/search.spec.js
app-web/src/components/Home/Masthead.js
app-web/src/components/Page/CardsContainer.js

Added some more tests for the algolia integration including asserting the algolia brand exists.

Additional e2e tests for algolia

---

app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/cypress/integration/Topics/index.spec.js
app-web/gatsby/onCreatePage.js
app-web/src/components/GithubTemplate/Masthead/Masthead.js
app-web/src/pages/topics.js
app-web/src/utils/helpers.js

Fix a bug that would prevent the topics page from rendering

update gatsby create page statement

---

.github/workflows/cypress.yml
app-web/__tests__/components/Masthead.test.js
app-web/cypress/integration/Home/search.spec.js
app-web/cypress/integration/auth.spec.js
app-web/cypress/support/commands.js
app-web/package-lock.json
app-web/package.json
app-web/src/AuthContext.js
app-web/src/components/DynamicSearchResults/index.js
app-web/src/pages/index.js
app-web/src/utils/hooks.js

Fixes #1257 
- fix buggy  implicitAuth react hook
- made some small  optimizations in the search gate **hook** to prevent it being called unless a user is authenticated and there  is a search query
- also made a refactor if implicitAuth hook to handle the entire lifecycle of login/logout and verified with e2e tests

Fix unable to  logout from devhub

---

app-web/gatsby/onCreateNode.js
app-web/plugins/gatsby-source-github-all/__tests__/__snapshots__/sourceNodes.test.js.snap
app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
app-web/plugins/gatsby-source-github-all/utils/createNode.js
app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
app-web/src/constants/ui.js
app-web/src/utils/algolia.js
app-web/topicRegistry/community-and-events.json

Added Lab Ops link to devhub
- also updated the siphon code so that it allows for tags to be used
- updated so that algolia indexes tags for websites

Add Lab Ops Learning to Topic

---

openshift/templates/bc.yaml

Tuned the `bc.yaml` file to reduce requests during the gatsby build. 
Fixes #1250

Reduce memory request and cpu requests

---

.github/ISSUE_TEMPLATE/content_suggestion.md
docs/content_contribution_sla.md
docs/registry.md

Updated/added docs in prep to surface them in the devhub for content contributors
- updated registry.md
- added a small sla
- added a github issue template

Add content contribution docs

---

app-web/gatsby-config.js
app-web/package-lock.json
app-web/package.json
app-web/src/constants/ui.js
app-web/topicRegistry/community-contributed.json
docs/registry.md

Added doc as well as a remark plugin to allow external links to open up in new tabs :)
Fixes #1271 
Fixes #1253 
Fixes #1252

Add Contributor doc to Community Contributed Topic

---

app-web/__tests__/components/ResourcePreview.test.js
app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
app-web/__tests__/pages/Index.test.js
app-web/cypress/integration/Home/search.spec.js
app-web/package-lock.json
app-web/package.json
app-web/src/components/Home/ResourcePreview.js
app-web/src/components/Home/TopicsPreview.js
app-web/src/components/Home/index.js
app-web/src/components/Search/SearchResults.js

Fixes #1245 
- updated E2E test and verified works

Fix filters not resetting on new searches

---

app-web/__tests__/components/__snapshots__/404.test.js.snap
app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
app-web/__tests__/components/__snapshots__/PrimaryHeader.test.js.snap
app-web/__tests__/hoc/__snapshots__/LayoutComponent.test.js.snap
app-web/__tests__/pages/__snapshots__/topics.test.js.snap
app-web/gatsby-config.js
app-web/src/components/UI/Pill/index.js
app-web/src/constants/designTokens.js
app-web/src/templates/StandAlone_GitHubRaw.js

Fixes issue #1282 
Detailed views on cards now include journey names

Improve card view to include journey name

---

app-web/__tests__/gatsby/__snapshots__/validators.test.js.snap
app-web/__tests__/gatsby/validators.test.js
app-web/cypress/integration/validations.spec.js
app-web/devhub.config.json
app-web/gatsby/createPages.js
app-web/gatsby/createResolvers.js
app-web/gatsby/createSchemaCustomization.js
app-web/gatsby/onCreateNode.js
app-web/gatsby/resolvers/devhubTopic.js
app-web/gatsby/utils/validators.js
app-web/jest.config.js
docs/registry.md

Prevents a github raw node from being created if their slugs conflict

---

.github/actions/devhub-markdown-frontmatter-verify/README.md
.github/actions/devhub-markdown-frontmatter-verify/package-lock.json
.github/actions/devhub-markdown-frontmatter-verify/package.json
.github/actions/devhub-markdown-frontmatter-verify/src/__tests__/index.test.js
.github/actions/devhub-markdown-frontmatter-verify/src/run.js
.github/workflows/devhub-markdown-test.yaml

Add throttling to github action to prevent abuse  of  github api

---

app-web/topicRegistry/developer-tools.json

Adding a link out to a placeholder document about Microsoft Dynamics 365
- provided link to tagged document

Add a tile for Andy about Dynamics

---

app-web/src/assets/blog/integratingAlgolia.md
app-web/topicRegistry/community-contributed.json

Add algolia docs to community contributed :)

Add docs on algolia

---

docs/searchWithAlgolia.md

Updating algolia docs, to include cloning a algolia index to local, when the index for a pr is changed

Updating Algolia Docs

---

app-web/src/components/Search/SearchResults.js
app-web/topicRegistry/platform-service-migration.json

Update Registry Docs for Platform Service Migration Page on devhub

Updated registry

---

algolia/index.json
app-web/__tests__/utils/algolia.test.js
app-web/src/templates/StandAlone_GitHubRaw.js
app-web/src/utils/algolia.js
app-web/src/utils/hooks.js

Persona Pill Resources

---

app-web/topicRegistry/collaboration-tools.json

Adding DRAFT to Colab tools topic title
-
-
-

- add DRAFT to topic title.

---

app-web/src/templates/StandAlone_GitHubRaw.js

Fix Design System Component Preview

---

app-web/topicRegistry/getting-started-on-the-devops-platform.json

Adding that doc that outlines all the stuff that newly onboarded teams should know.

add onboarding doc

---

app-web/src/pages/index.js

Fix title being stuck on single resource

---

app-web/topicRegistry/code-management.json

Fix an issue caused by web source containing no title

Adding title to source

---

app-web/journeyRegistry/onboarding.json
app-web/journeys/onboarding.md

added a new journey to help smooth out the onboarding process.

added onboarding journey

---

app-web/src/constants/ui.js
app-web/src/utils/helpers.js
app-web/topicRegistry/getting-started-on-the-devops-platform.json

Add status.developer.gov.bc.ca to devhub

Add platform status page to application

---

app-web/topicRegistry/design-system.json

Added browser support document to topic

---

app-web/topicRegistry/developer-tools.json

add checklists

---

app-web/topicRegistry/design-system.json

adding banner documentation

---

api/.babelrc
api/.pipeline/lib/config.js
api/__tests__/healthcheck.test.js
api/openshift/dc.yaml
api/package-lock.json
api/package.json
api/src/index.js
api/src/routers/healthcheck.js
api/src/serve.js

Added a testing framework with a simple test against the only endpoint we have right now (ehlo). 
Also added a readiness probe to the deployment config :)

Devhub-Api Testing Framework

---

api/.env.example
api/.pipeline/lib/deploy.js
api/openshift/dc.yaml
api/package-lock.json
api/package.json
api/src/index.js
api/src/routers/healthcheck.js

Enable cors between devhub and our microservice and generate pull request using the github api

Enable Cors on Devhub-API

---

.github/workflows/cypress.yml
.github/workflows/nodejs.yml
Jenkinsfile
algolia/index.json
api/Jenkinsfile
app-web/src/components/DynamicSearchResults/GithubIssueCardHeader.js
app-web/src/components/Search/SearchGateResults.js

The github issue/repo search results did not show the external link icon. This has been added. 
Fixes #969

Github Issue/Repo cards now show an external link icon

---

app-web/topicRegistry/getting-started-on-the-devops-platform.json

Added tags so status page is more searchable!
Fixes #1349

add tags to status page

---

app-web/gatsby/onCreatePage.js

A PR to trigger re-build for the Devhub so that the content can be updated.

Trigger Rebuild

---

api/.env.example
api/.pipeline/lib/deploy.js
api/__tests__/utils.test.js
api/openshift/dc.yaml
api/package-lock.json
api/src/index.js
api/src/utils/cors.js

added CORS_ORIGIN and CORS_PATTERN variables.
This allows dev/test/prod devhub deployments to access the devhub-api

Update api infracode to contain cors origin vars

---

api/.env.example
api/package-lock.json
api/package.json
api/src/constants.js
api/src/controllers/createTopic.js
api/src/controllers/editTopic.js
api/src/controllers/topics.js
api/src/index.js
api/src/routers/editTopic.js
api/src/routers/topics.js
api/src/utils/github.js
api/src/utils/githubhandler.js

Enable the Devhub API, to edit topics and make a pull request.

Edit a topic functionality for devhub api

---

CODEOWNERS

Edited CODEOWNERS file and removed my handle as I am no longer directly involved in this project.
-
-
-

Removing myself as a code owner.

---

README.md
app-web/package-lock.json
app-web/src/hoc/withResourceQuery.js
app-web/src/pages/index.js
app-web/src/templates/events.js
app-web/src/templates/pastEvents.js

Our install instructions were a bit vague. Andrew and I updated them
TODO:
- modify CODE_OWNERS fiel and remove Jas29

Update Installation Instructions

---

.github/helpers/kc-create-client.sh
.github/helpers/kc-delete-client.sh
.github/helpers/new-client.json
.github/workflows/deploy-web-to-dev.yml
openshift/templates/supporting-infrastructure/keycloak.secret.yaml

Integrate keycloak client creation for every devhub web deployment in the dev namespace

Keycloak client creation

---

app-web/topicRegistry/cloud-migration.json

topics include:
- jenkins migration
- image migration
- tips/tricks

Add cloud migration topic to the devhub

---

app-web/topicRegistry/data-and-apis.json
app-web/topicRegistry/developer-tools.json

adding BC Web Mapping and Spatial Services to two files 
(developer-tools and data-and-apis.json)
mvp - could be modified, perhaps add some tags and labels? - first attempt :)
@patricksimonian - based on your suggestions here is the pull request

adding BC Web Mapping and Spatial Services to topics

---

.github/helpers/clone_algolia_index.sh
.github/helpers/delete_algolia_index.sh
.github/helpers/github_env_to_algolia_index_suffix.sh
.github/workflows/promote-web.yml

include algollia index promotion

include algolia index cloning

---

.github/workflows/promote-web.yml
app-web/topicRegistry/code-management.json

SSO_BASE_URL and ALGOLIA_INDEX where incorrect for prod and test instances

Fixup bad variables in promotion script

---

.deploytronrc

add deploy tron config

---

web/topicRegistry/developer-tools.json

This PR is to add a new source to Developer Tools topic for BCGov Cloud Pathfinder team (Ticket#620).
-
-
-

Add a new source for Cloud-Pathfinder team

---

web/topicRegistry/community-and-events.json
web/topicRegistry/community-contributed.json

Add [Platform services sprint review demos](https://github.com/BCDevOps/openshift-wiki/blob/master/docs/HowTo/PlatformServicesSprintReviewDemos.md) to the devhub

add sprint review repo

---

web/topicRegistry/getting-started-on-the-devops-platform.json

Add load testing guidelines to the devhub

add load testing doc

---

README.md

Empty PR to update the contents of https://developer.gov.bc.ca/Platform-Services-Sprint-Review-Demo-Collection

add empty space to create pr

---

web/src/constants/ui.js
web/topicRegistry/getting-started-on-the-devops-platform.json

add ocp4 service overview to featured content

add ocp4 service overview to featured content

---

web/topicRegistry/getting-started-on-the-devops-platform.json

add https://github.com/BCDevOps/openshift-wiki/blob/master/docs/HowTo/UsefulProTips.md to the devhub

add openshift sefulProTips

---

web/src/constants/ui.js

Add [service definition](https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/OCPServiceDefinition.md) to 2nd position in featured content

add service definition to featured content

---

web/topicRegistry/authentication-and-authorization.json

removed repository link and added service overview

---

.github/workflows/devhub-scheduled-build-cleanup.yml
.github/workflows/devhub-scheduled-build.yml

- scheduled builds
- scheduled cleanup
-

Update ci/cd to include scheduled builds and scheduled cleanup

---

.github/workflows/devhub-scheduled-build.yml
openshift/templates/web/bc.yaml

- remove imagechange trigger from buildconfig to prevent infinite triggering
- fix a wrong ref to namespace from workflow

Fix CI issue

---

web/topicRegistry/developer-tools.json

update the link to new sysdig docs
- update the link to new sysdig docs
-
-

update pointer to sysdig doc

---

web/topicRegistry/developer-tools.json

uptime.com repo migration (this doc is not included in new doc site yet, we need to discuss if it should)
- ref updated
-
-

Update uptime doc ref

---

.github/workflows/deploy-web-to-dev.yml
web/topicRegistry/developer-tools.json

Per request from team, we are updating the link associated with the API Gateway. 
-
-
-

Update location of API Gateway documentation.

---

CODEOWNERS

This is to remove unrelated code owners from devhub repo.
- Myself, Billy and Tyler have been removed from code owner list
-
-

remove previous code owners

---

.gitignore
web/src/html.js

Added robots "noindex" meta tag
-
-
-

Devx 1132 - Remove classic dev hub from search index
